name: Terraform Import Secret

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: cd terraform-secrets && terraform init

    - name: Import SSH key
      run: |
        cd terraform-secrets
        terraform import azurerm_key_vault_secret.ssh_key "https://keyvault-kv-cloud23.vault.azure.net/secrets/sshpublickey/d09aafc2c1604c41a34495fa01a10881"
