name: Terraform Secrets Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: none

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure CLI login (manual classic SP)
      run: |
        az login --service-principal \
                 --username ${{ secrets.AZURE_CLIENT_ID }} \
                 --password ${{ secrets.AZURE_CLIENT_SECRET }} \
                 --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init (explicit backend config)
      run: |
        cd terraform-secrets
        terraform init -input=false -reconfigure \
          -backend-config="resource_group_name=tf-backend-rg" \
          -backend-config="storage_account_name=tfbackendstorage7791" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform-secrets.tfstate"

    - name: Debug .terraform contents
      run: |
        cd terraform-secrets
        echo "Contents of .terraform:"
        ls -la .terraform || echo ".terraform directory missing"
        echo "Backend config (if present):"
        cat .terraform/terraform.tfstate || echo "No local tfstate file found"

    - name: Select Terraform Workspace
      run: |
        cd terraform-secrets
        terraform workspace select default

    - name: Debug Terraform State
      run: |
        cd terraform-secrets
        terraform state list || echo "No remote state available"

    - name: Terraform Apply
      run: |
        cd terraform-secrets
        terraform apply -input=false --auto-approve \
          -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
          -var="client_object_id=${{ secrets.AZURE_CLIENT_OBJECT_ID }}"
